using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class GameManager : MonoBehaviour
{
    private static GameManager _instance;
    public static GameManager Instance { get { return _instance; } }
  
    private void Awake()
    {
        if (_instance != null && _instance != this)
        {
            Destroy(this.gameObject);
        }
        else
        {
            _instance = this;
            DontDestroyOnLoad(gameObject);
        }
            
    }
    public int levelCoinMultiplier = 2;
    private void OnEnable()
    {
        EventManager.OnGameOver.AddListener(GameOver);
    }
    private void OnDisable()
    {
        EventManager.OnGameOver.RemoveListener(GameOver);
    }
    public void GameOver()
    {
        int buildIndex = SceneManager.GetActiveScene().buildIndex +1;
        if (!Application.CanStreamedLevelBeLoaded(buildIndex))
        {
            buildIndex = 0;
        }

        SceneManager.LoadScene(buildIndex);
    }
}

